try {
    ab();
}
catch (e) {
    console.log("Error :" + e.name);
}
